/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : MessageId,
  'content' : string,
  'role' : Role,
  'timestamp' : Timestamp,
}
export type Difficulty = { 'advanced' : null } |
  { 'easy' : null } |
  { 'medium' : null };
export type MessageId = bigint;
export type PlanId = bigint;
export type PoseId = bigint;
export interface PoseIdeaPublic {
  'id' : PoseId,
  'difficulty' : Difficulty,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'isFavorite' : boolean,
  'savedAt' : Timestamp,
}
export type Role = { 'user' : null } |
  { 'assistant' : null };
export interface ShootPlanPublic {
  'id' : PlanId,
  'poseIds' : Array<PoseId>,
  'scheduledDate' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : string,
  'location' : string,
  'shotList' : Array<string>,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'displayName' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'photoCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addChatMessage' : ActorMethod<[string, string], ChatMessage>,
  'askAI' : ActorMethod<[string, Array<[string, string]>], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearChatHistory' : ActorMethod<[], boolean>,
  'createPose' : ActorMethod<
    [string, string, Difficulty, Array<string>],
    PoseIdeaPublic
  >,
  'createShootPlan' : ActorMethod<
    [string, string, [] | [string], Array<PoseId>, string],
    ShootPlanPublic
  >,
  'deletePose' : ActorMethod<[PoseId], boolean>,
  'deleteShootPlan' : ActorMethod<[PlanId], boolean>,
  'duplicateShootPlan' : ActorMethod<[PlanId, string], [] | [ShootPlanPublic]>,
  'favoritePose' : ActorMethod<[PoseId], boolean>,
  'generatePoseIdeas' : ActorMethod<[string, bigint], string>,
  'generateShootPlan' : ActorMethod<[string, string, Array<string>], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getPoses' : ActorMethod<[], Array<PoseIdeaPublic>>,
  'getProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getShootPlan' : ActorMethod<[PlanId], [] | [ShootPlanPublic]>,
  'getShootPlans' : ActorMethod<[], Array<ShootPlanPublic>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfilePublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'setOpenAIKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePose' : ActorMethod<
    [PoseId, string, string, Difficulty, Array<string>],
    [] | [PoseIdeaPublic]
  >,
  'updateProfile' : ActorMethod<[string], UserProfilePublic>,
  'updateShootPlan' : ActorMethod<
    [
      PlanId,
      string,
      string,
      [] | [string],
      Array<PoseId>,
      Array<string>,
      string,
    ],
    [] | [ShootPlanPublic]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];