/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MessageId = IDL.Nat;
export const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
export const Timestamp = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'role' : Role,
  'timestamp' : Timestamp,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'advanced' : IDL.Null,
  'easy' : IDL.Null,
  'medium' : IDL.Null,
});
export const PoseId = IDL.Nat;
export const PoseIdeaPublic = IDL.Record({
  'id' : PoseId,
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isFavorite' : IDL.Bool,
  'savedAt' : Timestamp,
});
export const PlanId = IDL.Nat;
export const ShootPlanPublic = IDL.Record({
  'id' : PlanId,
  'poseIds' : IDL.Vec(PoseId),
  'scheduledDate' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : IDL.Text,
  'location' : IDL.Text,
  'shotList' : IDL.Vec(IDL.Text),
});
export const UserId = IDL.Principal;
export const UserProfilePublic = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'photoCount' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [ChatMessage], []),
  'askAI' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearChatHistory' : IDL.Func([], [IDL.Bool], []),
  'createPose' : IDL.Func(
      [IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
      [PoseIdeaPublic],
      [],
    ),
  'createShootPlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(PoseId), IDL.Text],
      [ShootPlanPublic],
      [],
    ),
  'deletePose' : IDL.Func([PoseId], [IDL.Bool], []),
  'deleteShootPlan' : IDL.Func([PlanId], [IDL.Bool], []),
  'duplicateShootPlan' : IDL.Func(
      [PlanId, IDL.Text],
      [IDL.Opt(ShootPlanPublic)],
      [],
    ),
  'favoritePose' : IDL.Func([PoseId], [IDL.Bool], []),
  'generatePoseIdeas' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
  'generateShootPlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getPoses' : IDL.Func([], [IDL.Vec(PoseIdeaPublic)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getShootPlan' : IDL.Func([PlanId], [IDL.Opt(ShootPlanPublic)], ['query']),
  'getShootPlans' : IDL.Func([], [IDL.Vec(ShootPlanPublic)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePose' : IDL.Func(
      [PoseId, IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
      [IDL.Opt(PoseIdeaPublic)],
      [],
    ),
  'updateProfile' : IDL.Func([IDL.Text], [UserProfilePublic], []),
  'updateShootPlan' : IDL.Func(
      [
        PlanId,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(PoseId),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Opt(ShootPlanPublic)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MessageId = IDL.Nat;
  const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Timestamp = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'role' : Role,
    'timestamp' : Timestamp,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'advanced' : IDL.Null,
    'easy' : IDL.Null,
    'medium' : IDL.Null,
  });
  const PoseId = IDL.Nat;
  const PoseIdeaPublic = IDL.Record({
    'id' : PoseId,
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isFavorite' : IDL.Bool,
    'savedAt' : Timestamp,
  });
  const PlanId = IDL.Nat;
  const ShootPlanPublic = IDL.Record({
    'id' : PlanId,
    'poseIds' : IDL.Vec(PoseId),
    'scheduledDate' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'notes' : IDL.Text,
    'location' : IDL.Text,
    'shotList' : IDL.Vec(IDL.Text),
  });
  const UserId = IDL.Principal;
  const UserProfilePublic = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'photoCount' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [ChatMessage], []),
    'askAI' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearChatHistory' : IDL.Func([], [IDL.Bool], []),
    'createPose' : IDL.Func(
        [IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
        [PoseIdeaPublic],
        [],
      ),
    'createShootPlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(PoseId), IDL.Text],
        [ShootPlanPublic],
        [],
      ),
    'deletePose' : IDL.Func([PoseId], [IDL.Bool], []),
    'deleteShootPlan' : IDL.Func([PlanId], [IDL.Bool], []),
    'duplicateShootPlan' : IDL.Func(
        [PlanId, IDL.Text],
        [IDL.Opt(ShootPlanPublic)],
        [],
      ),
    'favoritePose' : IDL.Func([PoseId], [IDL.Bool], []),
    'generatePoseIdeas' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'generateShootPlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getPoses' : IDL.Func([], [IDL.Vec(PoseIdeaPublic)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getShootPlan' : IDL.Func([PlanId], [IDL.Opt(ShootPlanPublic)], ['query']),
    'getShootPlans' : IDL.Func([], [IDL.Vec(ShootPlanPublic)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePose' : IDL.Func(
        [PoseId, IDL.Text, IDL.Text, Difficulty, IDL.Vec(IDL.Text)],
        [IDL.Opt(PoseIdeaPublic)],
        [],
      ),
    'updateProfile' : IDL.Func([IDL.Text], [UserProfilePublic], []),
    'updateShootPlan' : IDL.Func(
        [
          PlanId,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(PoseId),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Opt(ShootPlanPublic)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };