/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PoseIdeaPublic {
    id: PoseId;
    difficulty: Difficulty;
    name: string;
    tags: Array<string>;
    description: string;
    isFavorite: boolean;
    savedAt: Timestamp;
}
export interface ShootPlanPublic {
    id: PlanId;
    poseIds: Array<PoseId>;
    scheduledDate?: string;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notes: string;
    location: string;
    shotList: Array<string>;
}
export interface UserProfilePublic {
    displayName: string;
    userId: UserId;
    createdAt: Timestamp;
    photoCount: bigint;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface http_header {
    value: string;
    name: string;
}
export type MessageId = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ChatMessage {
    id: MessageId;
    content: string;
    role: Role;
    timestamp: Timestamp;
}
export type PoseId = bigint;
export type PlanId = bigint;
export enum Difficulty {
    advanced = "advanced",
    easy = "easy",
    medium = "medium"
}
export enum Role {
    user = "user",
    assistant = "assistant"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addChatMessage(role: string, content: string): Promise<ChatMessage>;
    askAI(prompt: string, history: Array<[string, string]>): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearChatHistory(): Promise<boolean>;
    createPose(name: string, description: string, difficulty: Difficulty, tags: Array<string>): Promise<PoseIdeaPublic>;
    createShootPlan(name: string, location: string, scheduledDate: string | null, poseIds: Array<PoseId>, notes: string): Promise<ShootPlanPublic>;
    deletePose(id: PoseId): Promise<boolean>;
    deleteShootPlan(id: PlanId): Promise<boolean>;
    duplicateShootPlan(id: PlanId, newName: string): Promise<ShootPlanPublic | null>;
    favoritePose(id: PoseId): Promise<boolean>;
    generatePoseIdeas(theme: string, count: bigint): Promise<string>;
    generateShootPlan(planName: string, location: string, poseNames: Array<string>): Promise<string>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatHistory(): Promise<Array<ChatMessage>>;
    getPoses(): Promise<Array<PoseIdeaPublic>>;
    getProfile(): Promise<UserProfilePublic | null>;
    getShootPlan(id: PlanId): Promise<ShootPlanPublic | null>;
    getShootPlans(): Promise<Array<ShootPlanPublic>>;
    getUserProfile(user: Principal): Promise<UserProfilePublic | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(displayName: string): Promise<void>;
    setOpenAIKey(apiKey: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updatePose(id: PoseId, name: string, description: string, difficulty: Difficulty, tags: Array<string>): Promise<PoseIdeaPublic | null>;
    updateProfile(displayName: string): Promise<UserProfilePublic>;
    updateShootPlan(id: PlanId, name: string, location: string, scheduledDate: string | null, poseIds: Array<PoseId>, shotList: Array<string>, notes: string): Promise<ShootPlanPublic | null>;
}
import type { ChatMessage as _ChatMessage, Difficulty as _Difficulty, MessageId as _MessageId, PlanId as _PlanId, PoseId as _PoseId, PoseIdeaPublic as _PoseIdeaPublic, Role as _Role, ShootPlanPublic as _ShootPlanPublic, Timestamp as _Timestamp, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addChatMessage(arg0: string, arg1: string): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.addChatMessage(arg0, arg1);
                return from_candid_ChatMessage_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChatMessage(arg0, arg1);
            return from_candid_ChatMessage_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async askAI(arg0: string, arg1: Array<[string, string]>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.askAI(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askAI(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearChatHistory(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChatHistory();
            return result;
        }
    }
    async createPose(arg0: string, arg1: string, arg2: Difficulty, arg3: Array<string>): Promise<PoseIdeaPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createPose(arg0, arg1, to_candid_Difficulty_n7(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_PoseIdeaPublic_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPose(arg0, arg1, to_candid_Difficulty_n7(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_PoseIdeaPublic_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createShootPlan(arg0: string, arg1: string, arg2: string | null, arg3: Array<PoseId>, arg4: string): Promise<ShootPlanPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createShootPlan(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_ShootPlanPublic_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShootPlan(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_ShootPlanPublic_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePose(arg0: PoseId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePose(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePose(arg0);
            return result;
        }
    }
    async deleteShootPlan(arg0: PlanId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShootPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShootPlan(arg0);
            return result;
        }
    }
    async duplicateShootPlan(arg0: PlanId, arg1: string): Promise<ShootPlanPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateShootPlan(arg0, arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateShootPlan(arg0, arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async favoritePose(arg0: PoseId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.favoritePose(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.favoritePose(arg0);
            return result;
        }
    }
    async generatePoseIdeas(arg0: string, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePoseIdeas(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePoseIdeas(arg0, arg1);
            return result;
        }
    }
    async generateShootPlan(arg0: string, arg1: string, arg2: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateShootPlan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateShootPlan(arg0, arg1, arg2);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoses(): Promise<Array<PoseIdeaPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoses();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoses();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShootPlan(arg0: PlanId): Promise<ShootPlanPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShootPlan(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShootPlan(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShootPlans(): Promise<Array<ShootPlanPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShootPlans();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShootPlans();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setOpenAIKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAIKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAIKey(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePose(arg0: PoseId, arg1: string, arg2: string, arg3: Difficulty, arg4: Array<string>): Promise<PoseIdeaPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePose(arg0, arg1, arg2, to_candid_Difficulty_n7(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePose(arg0, arg1, arg2, to_candid_Difficulty_n7(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: string): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
    async updateShootPlan(arg0: PlanId, arg1: string, arg2: string, arg3: string | null, arg4: Array<PoseId>, arg5: Array<string>, arg6: string): Promise<ShootPlanPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShootPlan(arg0, arg1, arg2, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShootPlan(arg0, arg1, arg2, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ChatMessage_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PoseIdeaPublic_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PoseIdeaPublic): PoseIdeaPublic {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ShootPlanPublic_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShootPlanPublic): ShootPlanPublic {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShootPlanPublic]): ShootPlanPublic | null {
    return value.length === 0 ? null : from_candid_ShootPlanPublic_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PoseIdeaPublic]): PoseIdeaPublic | null {
    return value.length === 0 ? null : from_candid_PoseIdeaPublic_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PoseId;
    difficulty: _Difficulty;
    name: string;
    tags: Array<string>;
    description: string;
    isFavorite: boolean;
    savedAt: _Timestamp;
}): {
    id: PoseId;
    difficulty: Difficulty;
    name: string;
    tags: Array<string>;
    description: string;
    isFavorite: boolean;
    savedAt: Timestamp;
} {
    return {
        id: value.id,
        difficulty: from_candid_Difficulty_n11(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        tags: value.tags,
        description: value.description,
        isFavorite: value.isFavorite,
        savedAt: value.savedAt
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlanId;
    poseIds: Array<_PoseId>;
    scheduledDate: [] | [string];
    name: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    notes: string;
    location: string;
    shotList: Array<string>;
}): {
    id: PlanId;
    poseIds: Array<PoseId>;
    scheduledDate?: string;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notes: string;
    location: string;
    shotList: Array<string>;
} {
    return {
        id: value.id,
        poseIds: value.poseIds,
        scheduledDate: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.scheduledDate)),
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        notes: value.notes,
        location: value.location,
        shotList: value.shotList
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    content: string;
    role: _Role;
    timestamp: _Timestamp;
}): {
    id: MessageId;
    content: string;
    role: Role;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        content: value.content,
        role: from_candid_Role_n3(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    advanced: null;
} | {
    easy: null;
} | {
    medium: null;
}): Difficulty {
    return "advanced" in value ? Difficulty.advanced : "easy" in value ? Difficulty.easy : "medium" in value ? Difficulty.medium : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): Role {
    return "user" in value ? Role.user : "assistant" in value ? Role.assistant : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PoseIdeaPublic>): Array<PoseIdeaPublic> {
    return value.map((x)=>from_candid_PoseIdeaPublic_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShootPlanPublic>): Array<ShootPlanPublic> {
    return value.map((x)=>from_candid_ShootPlanPublic_n14(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    advanced: null;
} | {
    easy: null;
} | {
    medium: null;
} {
    return value == Difficulty.advanced ? {
        advanced: null
    } : value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
